### ISSUE TITLE
`KillTargetFrontHoldclick` test seems to fail about half the time

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/FPSci#243]
I've noticed lately that the `KillTargetFrontHoldclick` test has been failing about half of the time.

I'm not sure why this is happening, and I'm not sure this is important to fix yet, but I wanted to open an issue to track the occurence of this problem when running `FPSci.text`. If you learn anything else about this failure, please post here.

**Comment by jspjutNV** [comment]
One possible reason for this is irregular frame rate, or lag spikes on the computer running the test. I haven't found a good way to check if this is what is causing the failure on my machine.

One way you can make this fail is by moving the mouse while the tests are running. This causes failure because the mouse is expected to be controlled by the test, and the test system doesn't turn off the mouse input, so any mouse input has the potential to cause unexpected testing behavior.

**Comment by bboudaoud-nv** [comment]
We should consider ways to modify these tests so that user mouse input doesn't impact the success/failure criteria. If the tests are primarily intended to be run on a headless "runner" machine, this is lower priority.

Generally speaking we should probably revisit our test infrastructure/approach with a more critical eye as we continue to develop new features and tests for FPSci.
