### ISSUE TITLE
Targets should be able to specify a color individually

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/FPSci#266]
Right now the session specifies colors, but it would also be nice to have a way to specify colors per target type.

Maybe this would be an optional parameter to override the session/experiment target color only if set in the target array.

**Comment by bboudaoud-nv** [comment]
We should be able to implement this using an approach similar to what is done for target models.  Instead of creating a single `m_materials` array in `FPSciApp::loadModels()` we should add entries to a `Table<String, Array<shared_ptr<UniversalMaterial>>>` (similar to the  the approach used for target models) to load per-target (ID) materials. This will increase memory consumption slightly, but creates the option for different materials for different (simultaneously displayed) targets.

The only remaining question I have is how session-specified colors should interact with these target specified colors. For now my assumption is that if a target doesn't have its colors specified it would fall back to the session value, but alternatively we could do the opposite (have session colors override the target colors). The downside of this approach is it doesn't allow recoloring individual targets.

It may reduce merge conflicts to wait to implement this until #279 is merged into master/making the changes on top of that branch.
