### ISSUE TITLE
Performance hitch early in runtime

### ISSUE THREAD

**Issue by bboudaoud-nv** [NVlabs/FPSci#375]
There is a known issue w/ a performance hitch around shooting at/eliminating the first target in a run of FPSci. We believe this may be related to how audio is loaded/played for the first time but have not confirmed this. Currently the issue is not (typically) a problem as the first target shot at/destroyed is typically a reference and thus the bug does not impact "true" data collection.

**Comment by jspjutNV** [comment]
I believe this is related to #275 .

**Comment by morgan3d** [comment]
FWIW, on other platforms I play all "streaming" sounds at game startup with
0 volume in order to force them to pre-load.

-m

**Comment by jspjutNV** [comment]
That's our plan as well. We just haven't gotten around to it because the impact has been minor enough since it's only the first sound. It's probably most annoying that it may be causing one of the automated tests to fail, though we haven't proven that. We do know that by changing the order of the tests, the failing test starts passing and a test moved earlier fails for similar reasons (click and hold).
